swagger: '2.0'
info:
  version: 1.0.0
  title: Documents API. Сервис для работы с платежными документами СДБО ФЛ
  description: API для работы с платежными документами
  contact:
    name: BANK RBK API team
    email: apiteam@bankrbk.kz
    url: 'http://www.bankrbk.kz'
host: 10.1.1.114
basePath: /v1/documents
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  oauth:
    type: oauth2
    flow: application
    tokenUrl: 'https://10.1.1.114/oauth/token'
    scopes:
      'documents:create': Создание документов
security:
  - oauth:
      - 'documents:create'
paths:
  /calculate:
    get:
      tags:
        - Расчет
      summary: Расчет параметров перевода
      description: Расчет параметров перевода
      operationId: documentСalculate()
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/TransferType'
        - $ref: '#/parameters/ValueDate'
        - name: senderAcc
          in: query
          description: Номер счета отправителя
          required: true
          type: string
          minLength: 20
          maxLength: 20
          pattern: '[KZ][0-9]{5}[A-Za-z0-9]{13}'
        - name: receiverAcc
          in: query
          description: Номер счета получателя
          required: true
          type: string
          minLength: 20
          maxLength: 20
          pattern: '[KZ][0-9]{5}[A-Za-z0-9]{13}'
        - name: amount
          in: query
          type: number
          format: double
          description: Сумма перевода
          minimum: 0
          exclusiveMinimum: true
          required: true
        - name: direction
          in: query
          type: string
          description: >-
            Тип суммы (debit - к списанию, credit - к зачислению ). Т.е.
            необходимо списать или зачислить
          required: true
          enum:
            - DEBIT
            - CREDIT
      responses:
        '200':
          description: Возвращает расчитанные параметры перевода.
          schema:
            $ref: '#/definitions/CalcResp'
        '400':
          description: Invalid Input
          schema:
            $ref: '#/definitions/Errors'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
  /internal:
    post:
      tags:
        - Создание перевода
      summary: Создание внутрибанковского перевода
      description: Создание внутрибанковского перевода
      operationId: internalDocument()
      produces:
        - application/json
      parameters:
        - in: body
          name: transfer
          description: Перевод который должен быть создан
          required: true
          schema:
            $ref: '#/definitions/InternalTransfer'
      responses:
        '202':
          description: >-
            Accepted for processing. Предусмотреть входящую точку для приема
            квитка со статусом документа. Банковская ситема будет присылать
            обновления статуса.
          schema:
            $ref: '#/definitions/DocumentStatus'
        '400':
          description: Invalid Input
          schema:
            $ref: '#/definitions/Errors'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
  /external:
    post:
      tags:
        - Создание перевода
      summary: Создание межбанковского перевода внутри РК
      description: Создание межбанковского перевода внутри РК
      operationId: externalDocument()
      produces:
        - application/json
      parameters:
        - in: body
          name: transfer
          description: Перевод который должен быть создан
          required: true
          schema:
            $ref: '#/definitions/ExternalTransfer'
      responses:
        '202':
          description: >-
            Accepted for processing. Предусмотреть входящую точку для приема
            квитка со статусом документа. Банковская ситема будет присылать
            обновления статуса.
          schema:
            $ref: '#/definitions/DocumentStatus'
        '400':
          description: Invalid Input
          schema:
            $ref: '#/definitions/Errors'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
  '/status/{docRef}':
    get:
      tags:
        - Статус перевода
      summary: Получение статуса перевода
      description: >-
        Предусмотреть входящую точку для приема квитка со статусом документа.
        Банковская ситема будет присылать обновления статуса, использовать
        функцию запроса статуса документа только при необходимости. Когда
        документ находится еще в обработке, может вернутся ошибка 404 (статус
        PENDIG)
      operationId: documentStatus()
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/DocRef'
      responses:
        '200':
          description: Возвращает статус перевода.
          schema:
            $ref: '#/definitions/DocumentStatus'
        '400':
          description: Invalid Input
          schema:
            $ref: '#/definitions/Errors'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
  '/receipt/{docRef}':
    get:
      tags:
        - Квитанция
      summary: Получение квитанции перевода
      description: >-
        Получение квитанции (чека) перевода. Когда документ находится еще в
        обработке, может вернутся ошибка 404 (статус PENDIG)
      operationId: documentReceipt()
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/DocRef'
      responses:
        '200':
          description: Возвращает статус перевода.
          schema:
            $ref: '#/definitions/DocumentReceipt'
        '400':
          description: Invalid Input
          schema:
            $ref: '#/definitions/Errors'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Errors'
parameters:
  DocRef:
    name: docRef
    in: path
    required: true
    type: string
    description: Уникальный идентификатор документа внешней системы
  TransferType:
    name: transferType
    in: query
    required: true
    type: string
    description: 'Тип перевода (INTERNAL - внутренний, EXTERNAL - внешний по РК)'
    enum:
      - INTERNAL
      - EXTERNAL
  ValueDate:
    name: valueDate
    in: query
    required: true
    type: string
    description: Дата валютирования
    format: date
definitions:
  CalcResp:
    type: object
    description: Расчитанные параметры перевода
    properties:
      debit:
        type: number
        format: double
        description: Сумма к списанию
        minimum: 0
        exclusiveMinimum: true
      credit:
        type: number
        format: double
        description: Сумма к зачислению
        minimum: 0
        exclusiveMinimum: true
      debitCurrency:
        type: string
        description: 'Буквенный код валюты списания (KZT, USD, EUR и т.д.)'
        minLength: 3
        maxLength: 3
        pattern: '[A-Z]{3}'
      creditCurrency:
        type: string
        description: 'Буквенный код валюты зачисления (KZT, USD, EUR и т.д.)'
        minLength: 3
        maxLength: 3
        pattern: '[A-Z]{3}'
      transferFee:
        type: number
        format: double
        description: 'Сумма комиссии за перевод, в валюте счета списания'
        minimum: 0
      isConversion:
        type: boolean
        description: Признак конвертации средств
      transferRate:
        type: object
        description: Cоотношение котировок валюты списания и зачисления.
        properties:
          srate:
            type: number
            format: double
            description: Котировка списания
            minimum: 0
            exclusiveMinimum: true
          drate:
            type: number
            format: double
            description: Котировка зачисления
            minimum: 0
            exclusiveMinimum: true
        required:
          - srate
          - drate
    required:
      - debit
      - credit
      - debitCurrency
      - creditCurrency
      - transferFee
      - isConversion
  Participant:
    type: object
    description: Участник перевода
    properties:
      account:
        type: string
        description: Номер счета
        minLength: 20
        maxLength: 20
        pattern: '[KZ][0-9]{5}[A-Za-z0-9]{13}'
      identificationNumber:
        type: string
        description: ИИН/БИН участника
        minLength: 12
        maxLength: 12
      name:
        type: string
        description: Наименование участника
        minLength: 1
      kp:
        type: string
        description: КОд плательщика/КБе бенефициара
        minLength: 2
        maxLength: 2
        pattern: '[0-9]{2}'
      bankBic:
        type: string
        description: БИК банка
        minLength: 8
        maxLength: 12
      bankName:
        type: string
        description: Наименование банка
        minLength: 8
        maxLength: 12
    required:
      - account
      - name
      - kp
      - bankBic
      - bankName
  InternalTransfer:
    type: object
    description: Внутрибанковский перевод
    properties:
      docRef:
        type: string
        description: Уникальный идентификатор документа внешней системы
        minLength: 1
        maxLength: 40
      system:
        type: string
        description: Уникальный код внешней системы (Для сдбо фл - dboretail)
        minLength: 1
        maxLength: 40
      documentDate:
        type: string
        format: date-time
        description: Дата документа
      valueDate:
        type: string
        format: date
        description: Дата валютирования документа
      senderAccount:
        type: string
        description: Номер счета отправителя
        minLength: 20
        maxLength: 20
        pattern: '[KZ][0-9]{5}[A-Za-z0-9]{13}'
      receiverAccount:
        type: string
        description: Номер счета получателя
        minLength: 20
        maxLength: 20
        pattern: '[KZ][0-9]{5}[A-Za-z0-9]{13}'
      paymentPurposeCode:
        type: string
        description: Код назначения платежа
        minLength: 3
        maxLength: 3
        pattern: '[0-9]{3}'
      paymentPurpose:
        type: string
        description: Назначения платежа
        minLength: 1
      amount:
        type: number
        format: double
        description: 'Сумма перевода, всега указывается в валюте счета списания.'
        minimum: 0
        exclusiveMinimum: true
      senderIdentificationNumber:
        type: string
        description: >-
          ИИН/БИН действующего клиента отправителя. Если указан осуществляется
          проверка идентификационного номера клиента отправителя на соответсвие
        minLength: 12
        maxLength: 12
      receiverIdentificationNumber:
        type: string
        description: >-
          ИИН/БИН владельца счета зачисления. Если указан осуществляется
          проверка идентификационного номера клиента получателя на соответсвие
        minLength: 12
        maxLength: 12
      transferFee:
        type: number
        format: double
        description: >-
          Сумма рассчитанной комиссии за перевод. Если указана, банковская
          система будет проверять не изменилась ли комиссия к моменту обработки.
          При изменении - документ будет отвергнут
        minimum: 0
      transferRate:
        type: object
        description: >-
          Cоотношение котировок валюты списания и зачисления. Если параметр
          указан, банковская система будет проверять не изменился ли курс к
          моменту обработки. При изменении - документ будет отвергнут
        properties:
          srate:
            type: number
            format: double
            description: Котировка списания
            minimum: 0
            exclusiveMinimum: true
          drate:
            type: number
            format: double
            description: Котировка зачисления
            minimum: 0
            exclusiveMinimum: true
        required:
          - srate
          - drate
    required:
      - docRef
      - system
      - documentDate
      - valueDate
      - senderAccount
      - receiverAccount
      - paymentPurposeCode
      - paymentPurpose
      - amount
  ExternalTransfer:
    type: object
    description: Межбанковский перевод внутри РК
    properties:
      docRef:
        type: string
        description: Уникальный идентификатор документа внешней системы
        minLength: 1
        maxLength: 40
      system:
        type: string
        description: Уникальный код внешней системы (Для сдбо фл - dboretail)
        minLength: 1
        maxLength: 40
      documentDate:
        type: string
        format: date-time
        description: Дата документа
      valueDate:
        type: string
        format: date
        description: Дата валютирования документа
      senderAccount:
        type: string
        description: Номер счета отправителя
        minLength: 20
        maxLength: 20
        pattern: '[KZ][0-9]{5}[A-Za-z0-9]{13}'
      receiver:
        $ref: '#/definitions/Participant'
      paymentPurposeCode:
        type: string
        description: Код назначения платежа
        minLength: 3
        maxLength: 3
        pattern: '[0-9]{3}'
      paymentPurpose:
        type: string
        description: Назначения платежа
        minLength: 1
      amount:
        type: number
        format: double
        description: 'Сумма перевода, всега указывается в валюте счета списания.'
        minimum: 0
        exclusiveMinimum: true
      cbc:
        type: string
        description: Код бюджетной классификации (Для платежей в бюджет)
        minLength: 1
      senderIdentificationNumber:
        type: string
        description: >-
          ИИН/БИН действующего клиента отправителя. Если указан осуществляется
          проверка идентификационного номера клиента отправителя на соответсвие
        minLength: 12
        maxLength: 12
      transferFee:
        type: number
        format: double
        description: >-
          Сумма рассчитанной комиссии за перевод. Если указана, банковская
          система будет проверять не изменилась ли комиссия к моменту обработки.
          При изменении - документ будет отвергнут
        minimum: 0
    required:
      - docRef
      - system
      - documentDate
      - valueDate
      - senderAccount
      - receiver
      - paymentPurposeCode
      - paymentPurpose
      - amount
  DocumentStatus:
    type: object
    description: Статус документа
    properties:
      docRef:
        type: string
        description: Уникальный идентификатор документа
        minLength: 1
        maxLength: 40
      status:
        type: string
        description: >-
          Статус документа (PENDING - ожидает обработки, ACCEPTED - принят в
          обработку, PROCESSED - Исполнен, DECLINED - Отвергнут)
        enum:
          - PENDING
          - ACCEPTED
          - PROCESSED
          - DECLINED
      message:
        type: string
        description: Сопроводительное сообщение от банка
    required:
      - docRef
      - status
  DocumentReceipt:
    type: object
    description: Межбанковский перевод внутри РК
    properties:
      docRef:
        type: string
        description: Уникальный идентификатор документа внешней системы
        minLength: 1
        maxLength: 40
      id:
        type: string
        description: Уникальный идентификатор документа
        minLength: 1
      status:
        type: string
        description: >-
          Статус документа (ACCEPTED - принят в обработку, PROCESSED - Исполнен,
          DECLINED - Отвергнут)
        enum:
          - ACCEPTED
          - PROCESSED
          - DECLINED
      documentDate:
        type: string
        format: date-time
        description: Дата документа
      valueDate:
        type: string
        format: date
        description: Дата валютирования документа
      sender:
        $ref: '#/definitions/Participant'
      receiver:
        $ref: '#/definitions/Participant'
      paymentPurposeCode:
        type: string
        description: Код назначения платежа
        minLength: 3
        maxLength: 3
        pattern: '[0-9]{3}'
      paymentPurpose:
        type: string
        description: Назначения платежа
        minLength: 1
      amount:
        type: number
        format: double
        description: 'Сумма перевода, всега указывается в валюте счета списания.'
        minimum: 0
        exclusiveMinimum: true
      cbc:
        type: string
        description: Код бюджетной классификации (Для платежей в бюджет)
        minLength: 1
    required:
      - docRef
      - id
      - documentDate
      - valueDate
      - sender
      - receiver
      - paymentPurposeCode
      - paymentPurpose
      - amount
  Error:
    type: object
    properties:
      code:
        type: integer
        description: Код ошибки
        format: int32
      type:
        type: string
        description: >-
          Тип ошибки. validation - ошибка бизнес логики. exception - техническая
          ошибка
        enum:
          - validation
          - exception
      message:
        type: string
        description: Текст ошибки
        minLength: 0
      details:
        type: string
        description: Детали ошибки. Опционально
        minLength: 0
    required:
      - code
      - type
      - message
  Errors:
    type: array
    minItems: 1
    items:
      $ref: '#/definitions/Error'
